### ISSUE TITLE
Cannot assume the role

### ISSUE THREAD

**Issue by jtrnegi** [monitoringartist/grafana-cross-account-cloudwatch-access#2]
There are 2 aws accounts in one grafana is running AWS Account A and on the other cloudwatch service is there Account B.

I logged in the account B and ran the cloudformation template and got the role arn and the external id , then I open the grafana GUI and pasted the same but got the error.

1. CloudWatch metrics query failed: AccessDenied: User: arn:aws:sts::accounta:assumed-role/svc-cha-grafana-pre-live-grafana-cloudwatch-ro/i-04b932bc0fe364205 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::accountb:role/govind-GrafanaRole-QD4MDTU0YDPT status code: 403, request id: 18c8f5d4-bb2e-40dd-88d2-62ca4fd3a703 

do I have to do something in the account a too.

**Comment by jangaraj** [comment]
Sorry, this is not an issue, but support request. Please contact your AWS support - you need configure your instance profile properly to assume that role.
